### ISSUE TITLE
android offline png Tile map 

### ISSUE THREAD

**Issue by Lighthouse-Yang** [Esri/arcgis-runtime-demos-android#57]
Dear developer, I would like to ask you how to load PNG Tile Map in offline status in Android. The pictures are placed in levels, horizontal and vertical coordinates, and there is no relevant configuration file

**Comment by TADraeseke** [comment]
Hi there! Can I ask you to please post your question in: https://community.esri.com/t5/arcgis-runtime-sdk-for-android-questions/bd-p/arcgis-runtime-sdk-for-android-questions

Fielding all questions in the same place helps all our users. Thanks!
